config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'homes#index'
  post 'homes/load_generation', controller: 'homes', action: 'load_generation'
  post 'homes/next_generation', controller: 'homes', action: 'next_generation'
  post 'homes/reset_generation', controller: 'homes', action: 'reset'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  include HomesHelper
  def index
    @grid = session[:grid] || []
  end

  def load_generation
    @grid = validate_csv_file(home_params[:file])
    session[:grid] = @grid || []
    respond_to do |format|
      if @grid
        format.html { redirect_to root_path, notice: 'Generation loaded' }
      else
        format.html { redirect_to root_path, alert: 'Generation not loaded, csv not valid' }
      end
    end
  end

  def next_generation
    @grid = validate_grid(session[:grid]) ? game_of_life(session[:grid]) : false
    session[:grid] = @grid || []
    respond_to do |format|
      if @grid
        format.html { redirect_to root_path, notice: 'New Generation' }
      else
        format.html { redirect_to root_path, notice: 'New Generation' }
      end
    end
  end

  def reset
    session[:grid] = []
  end

  def home_params
    params.require(:home).permit(:file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
  require 'csv'
  def validate_csv_file(file)
    return false unless file.content_type == 'text/csv'
    return false unless file.original_filename.split('.').last == 'csv'

    grid = CSV.open(file.path).each.to_a
    return false unless validate_grid(grid)

    grid
  end

  def validate_grid(grid)
    return false unless grid.length > 0

    grid.each do |row|
      return false unless row.length == grid.length && (row - %w[. *]).empty?
    end
    true
  end

  def game_of_life(grid)
    new_grid = []
    grid.each_with_index do |row, row_index|
      new_grid[row_index] = []
      row.each_with_index do |cell, cell_index|
        live_neighbours = get_live_neighbours([row_index, cell_index], grid)
        new_grid[row_index][cell_index] = check_rules(cell, live_neighbours)
      end
    end
    new_grid
  end

  # cell = [0,0]
  # grid = [
  # %w[* . .],
  # %w[* . *],
  # %w[. * .]
  # ]
  def get_live_neighbours(cell_coordinates, grid)
    live_neighbours = 0

    # this block circular matrix, change with xvals = [-1, 0, 1] and yvals = [-1, 0, 1] IF you don't want to use it
    xvals = get_xvals(cell_coordinates, grid)
    yvals = get_yvals(cell_coordinates, grid)

    yvals.each do |y|
      xvals.each do |x|
        next if x == 0 && y == 0

        next unless grid[cell_coordinates[0] + y][cell_coordinates[1] + x] == '*'

        live_neighbours += 1
      end
    end
    live_neighbours
  end

  # 1.Any live cell with fewer than two live neighbours dies.
  # 2.Any live cell with two or three live neighbours lives on to the next generation.
  # 3.Any live cell with more than three live neighbours dies.
  # 4.Any dead cell with exactly three live neighbours becomes a live cell.
  def check_rules(cell, live_neighbours)
    return '.' if cell == '*' && live_neighbours < 2
    return '*' if cell == '*' && [2, 3].include?(live_neighbours)
    return '.' if cell == '*' && live_neighbours > 3
    return '*' if cell == '.' && live_neighbours == 3

    cell
  end

  private

  # this block circular matrix, change with yvals = [-1, 0, 1]  IF you don't want to use it
  def get_yvals(cell_coordinates, grid)
    yvals = []
    yvals.push(-1) if cell_coordinates[0] > 0
    yvals.push 0
    yvals.push(+1) if cell_coordinates[0] < grid.length - 1
    yvals
  end

  # this block circular matrix, change with xvals = [-1, 0, 1]  IF you don't want to use it
  def get_xvals(cell_coordinates, grid)
    xvals = []
    xvals.push(-1) if cell_coordinates[1] > 0
    xvals.push 0
    xvals.push(+1) if cell_coordinates[1] < grid[1].length - 1
    xvals
  end
end

app/views/homes/index.html.erb
<div data-controller="homes">
  <% flash.each do |type, msg| %>
    <div>
      <%= msg %>
    </div>
  <% end %>
  <br>

  <div class="flex no-wrap">
    <div class="w-full">
      <%= form_for :home, url: "homes/load_generation" do |form| %>
        <%= form.label 'Load a valid csv' %>
        <%= form.file_field :file %>
        <%= form.button 'Load generation', data: { action: 'homes#stopTimer'} %>
      <% end %>
      <div class="flex flex-row">

        <%= button_to 'Start generation', homes_next_generation_path, method: :post, type: :button, id: 'next', data: { action: 'homes#startGeneration', 'homes-target':'next'}  %>
        <%= button_to 'Reset generation', homes_reset_generation_path, method: :post, type: :button  , data: { action: 'homes#stopTimer'}%>
      </div>
    </div>
    <br>
    <div class="w-full flex">
      <% @grid.each do |y| %>
        <div class="flex flex-col">
          <% y.each do |x| %>
            <div class="flex flex-row">
              <%= x %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Extendi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>